# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(
  email: 'mac@veryhappythings.co.uk',
  password: 'm',
  epiclan_id: 'maccy',
  is_admin: true
)

team = Team.create(name: 'Titan', abbreviation: 'Titan')
Player.create(team: team, name: 'kYxY', handle: 'kYxY')
Player.create(team: team, name: 'Ohaiyo', handle: 'Ohaiyo')
Player.create(team: team, name: 'Net', handle: 'Net')
Player.create(team: team, name: 'XtiNcT', handle: 'XtiNcT')
Player.create(team: team, name: 'YamateH', handle: 'YamateH')
team = Team.create(name: 'Evil Geniuses', abbreviation: 'EG')
Player.create(team: team, name: 'Mason', handle: 'Mason')
Player.create(team: team, name: 'Arteezy', handle: 'Arteezy')
Player.create(team: team, name: 'Universe', handle: 'Universe')
Player.create(team: team, name: 'zai', handle: 'zai')
Player.create(team: team, name: 'ppd', handle: 'ppd')
team = Team.create(name: 'NewBee', abbreviation: 'NewBee')
Player.create(team: team, name: 'Hao', handle: 'Hao')
Player.create(team: team, name: 'Mu', handle: 'Mu')
Player.create(team: team, name: 'xiao8', handle: 'xiao8')
Player.create(team: team, name: 'Banana', handle: 'Banana')
Player.create(team: team, name: 'Sansheng', handle: 'Sansheng')
team = Team.create(name: 'Vici Gaming', abbreviation: 'VG')
Player.create(team: team, name: 'Sylar', handle: 'Sylar')
Player.create(team: team, name: 'Super', handle: 'Super')
Player.create(team: team, name: 'rOtk', handle: 'rOtk')
Player.create(team: team, name: 'Fenrir', handle: 'Fenrir')
Player.create(team: team, name: 'fy', handle: 'fy')
team = Team.create(name: 'Natus Vincere', abbreviation: "Na'Vi")
Player.create(team: team, name: 'Puppey', handle: 'Puppey')
Player.create(team: team, name: 'XBOCT', handle: 'XBOCT')
Player.create(team: team, name: 'Dendi', handle: 'Dendi')
Player.create(team: team, name: 'Funn1k', handle: 'Funn1k')
Player.create(team: team, name: 'KuroKy', handle: 'KuroKy')
team = Team.create(name: 'Team DK', abbreviation: 'DK')
Player.create(team: team, name: 'BurNing', handle: 'BurNing')
Player.create(team: team, name: 'Mushi', handle: 'Mushi')
Player.create(team: team, name: 'iceiceice', handle: 'iceiceice')
Player.create(team: team, name: 'LaNm', handle: 'LaNm')
Player.create(team: team, name: 'X!!', handle: 'X!!')
team = Team.create(name: 'Invictus Gaming', abbreviation: 'iG')
Player.create(team: team, name: 'Luo', handle: 'Luo')
Player.create(team: team, name: 'Ferrari_430', handle: 'Ferrari_430')
Player.create(team: team, name: 'YYF', handle: 'YYF')
Player.create(team: team, name: 'ChauN', handle: 'ChauN')
Player.create(team: team, name: 'Faith', handle: 'Faith')
team = Team.create(name: 'Cloud9', abbreviation: 'C9')
Player.create(team: team, name: 'EternalEnVy', handle: 'EternalEnVy')
Player.create(team: team, name: 'SingSing', handle: 'SingSing')
Player.create(team: team, name: 'bOne7', handle: 'bOne7')
Player.create(team: team, name: 'Aui_2000', handle: 'Aui_2000')
Player.create(team: team, name: 'pieliedie', handle: 'pieliedie')
team = Team.create(name: 'LGD Gaming', abbreviation: 'LGD')
Player.create(team: team, name: 'DDC', handle: 'DDC')
Player.create(team: team, name: 'Yao', handle: 'Yao')
Player.create(team: team, name: 'DD', handle: 'DD')
Player.create(team: team, name: 'xiaotuji', handle: 'xiaotuji')
Player.create(team: team, name: 'Lin', handle: 'Lin')
