# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
team = Team.create(name: 'Titan', abbreviation: 'Titan')
Player.create(team: team, name: '', handle: 'kYxY')
Player.create(team: team, name: '', handle: 'Ohaiyo')
Player.create(team: team, name: '', handle: 'Net')
Player.create(team: team, name: '', handle: 'XtiNcT')
Player.create(team: team, name: '', handle: 'YamateH')
team = Team.create(name: 'Evil Geniuses', abbreviation: 'EG')
Player.create(team: team, name: '', handle: 'Mason')
Player.create(team: team, name: '', handle: 'Arteezy')
Player.create(team: team, name: '', handle: 'Universe')
Player.create(team: team, name: '', handle: 'zai')
Player.create(team: team, name: '', handle: 'ppd')
team = Team.create(name: 'NewBee', abbreviation: 'NewBee')
Player.create(team: team, name: '', handle: 'Hao')
Player.create(team: team, name: '', handle: 'Mu')
Player.create(team: team, name: '', handle: 'xiao8')
Player.create(team: team, name: '', handle: 'Banana')
Player.create(team: team, name: '', handle: 'Sansheng')
team = Team.create(name: 'Vici Gaming', abbreviation: 'VG')
Player.create(team: team, name: '', handle: 'Sylar')
Player.create(team: team, name: '', handle: 'Super')
Player.create(team: team, name: '', handle: 'rOtk')
Player.create(team: team, name: '', handle: 'Fenrir')
Player.create(team: team, name: '', handle: 'fy')
team = Team.create(name: 'Natus Vincere', abbreviation: "Na'Vi")
Player.create(team: team, name: '', handle: 'Puppey')
Player.create(team: team, name: '', handle: 'XBOCT')
Player.create(team: team, name: '', handle: 'Dendi')
Player.create(team: team, name: '', handle: 'Funn1k')
Player.create(team: team, name: '', handle: 'KuroKy')
team = Team.create(name: 'Team DK', abbreviation: 'DK')
Player.create(team: team, name: '', handle: 'BurNing')
Player.create(team: team, name: '', handle: 'Mushi')
Player.create(team: team, name: '', handle: 'iceiceice')
Player.create(team: team, name: '', handle: 'LaNm')
Player.create(team: team, name: '', handle: 'X!!')
team = Team.create(name: 'Invictus Gaming', abbreviation: 'iG')
Player.create(team: team, name: '', handle: 'Luo')
Player.create(team: team, name: '', handle: 'Ferrari_430')
Player.create(team: team, name: '', handle: 'YYF')
Player.create(team: team, name: '', handle: 'ChauN')
Player.create(team: team, name: '', handle: 'Faith')
team = Team.create(name: 'Cloud9', abbreviation: 'C9')
Player.create(team: team, name: '', handle: 'EternalEnVy')
Player.create(team: team, name: '', handle: 'SingSing')
Player.create(team: team, name: '', handle: 'bOne7')
Player.create(team: team, name: '', handle: 'Aui_2000')
Player.create(team: team, name: '', handle: 'pieliedie')
team = Team.create(name: 'LGD Gaming', abbreviation: 'LGD')
Player.create(team: team, name: '', handle: 'DDC')
Player.create(team: team, name: '', handle: 'Yao')
Player.create(team: team, name: '', handle: 'DD')
Player.create(team: team, name: '', handle: 'xiaotuji')
Player.create(team: team, name: '', handle: 'Lin')
